/**
 * Patches JSON Schemas generated by the MCP SDK so that mcpo (OpenAPI → Pydantic)
 * can process them without crashing.
 *
 * Two transformations are applied:
 *
 * 1. `definitions` → `$defs` (top-level key + `#/definitions/` $ref paths).
 *    zod-to-json-schema uses `definitions` by default; JSON Schema draft 2019-09+
 *    and mcpo expect `$defs`.
 *
 * 2. Path-based self-refs (`$ref: "#/properties/..."`) are replaced with `{}`
 *    (accept-anything schema). These arise from `z.lazy()` recursive schemas;
 *    Pydantic cannot resolve intra-document path refs during model construction.
 *    Replacing with `{}` preserves the structure for non-recursive branches while
 *    letting mcpo generate a working OpenAPI spec.
 */
export function rewriteDefinitionsToDefs(schema: unknown): unknown {
  if (!schema || typeof schema !== 'object' || Array.isArray(schema)) return schema;

  // Step 1 — rename #/definitions/ refs and the top-level key
  let json = JSON.stringify(schema)
    .replace(/"#\/definitions\//g, '"#/$defs/');
  const obj = JSON.parse(json) as Record<string, unknown>;
  if ('definitions' in obj) {
    obj.$defs = obj.definitions;
    delete obj.definitions;
  }

  // Step 2 — replace intra-document path refs ($ref: "#/...") with {}
  // These come from z.lazy() and cause Pydantic model builder to crash.
  // Only replace refs that are NOT $defs refs (those are fine).
  json = JSON.stringify(obj).replace(
    /\{"\$ref":"#\/(?!\$defs\/)([^"]+)"\}/g,
    '{}'
  );

  return JSON.parse(json) as unknown;
}
