/**
 * Patches JSON Schemas generated by the MCP SDK so that mcpo (OpenAPI → Pydantic)
 * can process them without crashing.
 *
 * Two transformations are applied:
 *
 * 1. `definitions` → `$defs` (top-level key + `#/definitions/` $ref paths).
 *    zod-to-json-schema uses `definitions` by default; JSON Schema draft 2019-09+
 *    and mcpo expect `$defs`.
 *
 * 2. Path-based self-refs (`$ref: "#/properties/..."`) are replaced with `{}`
 *    (accept-anything schema). These arise when zod-to-json-schema deduplicates
 *    shared sub-schemas via intra-document path refs. mcpo's Pydantic model builder
 *    asserts all $ref targets live in $defs and crashes on path refs.
 *    Replacing with `{}` preserves the structural slot while letting mcpo generate
 *    a working OpenAPI spec.
 */
export function rewriteDefinitionsToDefs(schema: unknown): unknown {
  if (!schema || typeof schema !== 'object' || Array.isArray(schema)) return schema;

  // Step 1 — rename #/definitions/ refs and the top-level key
  let json = JSON.stringify(schema)
    .replace(/"#\/definitions\//g, '"#/$defs/');
  const obj = JSON.parse(json) as Record<string, unknown>;
  if ('definitions' in obj) {
    obj.$defs = obj.definitions;
    delete obj.definitions;
  }

  // Step 2 — recursive walk: replace any object whose $ref points outside $defs with {}.
  // Regex-based replacement is unreliable when $ref objects have sibling keys
  // (e.g. additionalProperties) — the pattern {"$ref":"..."} stops matching.
  return replacePathRefs(obj);
}

function replacePathRefs(value: unknown): unknown {
  if (value === null || typeof value !== 'object') return value;
  if (Array.isArray(value)) return (value as unknown[]).map(replacePathRefs);

  const obj = value as Record<string, unknown>;

  // If this object carries a $ref pointing outside $defs, collapse it to accept-anything.
  if (typeof obj['$ref'] === 'string' && !obj['$ref'].startsWith('#/$defs/')) {
    return {};
  }

  const result: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(obj)) {
    result[k] = replacePathRefs(v);
  }
  return result;
}
